grails:
    plugins:
        twitterbootstrap:
            fixtaglib: true

headerAndFooter:
    baseURL: https://www.ala.org.au/commonui-bs5-2019
    # injects into the header a challenge.js script
    # <script type="text/javascript" src="challengeJsUrl" defer></script>
    challengeJsUrl:
    useMustache: true
    excludeBootstrapCss: true
    excludeAlaStylesCss: true
    excludeBootstrapJs: true
    excludeApplicationJs: true

userdetails:
    url: https://auth.ala.org.au/userdetails/
    profilePath: myprofile